services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: arq scheduler.main.WorkerSettings
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
